# Change these first
owner: ooliver1 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
user-agent: ooliver1

sites:
  - name: Tooty.xyz
    url: https://tooty.xyz
  - name: Boting.xyz
    url: https://boting.xyz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tooty.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/ooliver1/status/master/assets/tilcooks.png
  name: Status
  navbar:
    - title: Status
      href: /
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
